install: 
 - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
 - export PATH="$PATH:/$(cd)/depot_tools"
 - sh ./build/install-build-deps.sh --no-chromeos-fonts
 - gclient runhooks
 - gn gen out/Default
script: autoninja -C out/Default chrome
sudo: required
